# Generated by Django 3.2 on 2021-04-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='budgeted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='groups',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='groups',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='transactions',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
