# Generated by Django 3.2 on 2021-04-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetApp', '0002_auto_20210410_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='month',
            field=models.DateTimeField(default=4),
        ),
    ]
