# Generated by Django 3.2 on 2021-04-10 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetApp', '0003_alter_budgets_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BudgetApp.groups')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BudgetApp.transactions')),
            ],
        ),
        migrations.DeleteModel(
            name='GroupCategories',
        ),
    ]
