# Generated by Django 3.2 on 2021-04-11 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetApp', '0005_auto_20210410_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetApp.categories')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BudgetApp.groups')),
            ],
        ),
        migrations.DeleteModel(
            name='GroupTransactions',
        ),
    ]
