# Generated by Django 3.2 on 2021-04-11 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetApp', '0006_auto_20210410_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='budgeted',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='categories',
            name='remaining',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='categories',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='groupcategories',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BudgetApp.categories'),
        ),
    ]
