# Generated by Django 3.2 on 2021-04-11 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BudgetApp', '0007_auto_20210410_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='remaining',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='spent',
        ),
    ]
